#!/bin/sh

# stop programs associated with my mpd setup
pgrep -f '^bash .*/kunst$' | xargs kill -15 || echo 'kunst does not seem to be running'
pgrep -f '^cava$' | xargs kill -15 || echo 'cava does not seem to be running'
pgrep -f '^ncmpcpp$' | xargs kill -15 || echo 'ncmpcpp does not seem to be running'
pgrep -f "^/bin/sh $(command -v monitor-current-track)$" | xargs kill -15 || echo 'monitor-current-track does not seem to be running'
pgrep -f "^perl $(command -v clerk)$" | xargs kill -15 || echo 'clerk does not seem to be running'
pgrep -f '^projectM-pulseaudio$' | xargs kill -15 || echo 'projectM does not seem to be running'
systemctl stop --user cantata-dynamic
systemctl stop --user mpd-mpris
systemctl stop --user mpd
# vi:ft=sh
