#!/bin/sh

# Shows the current track playing along with its rating.
# Updates on player/sticker events.

while true; do
	now-playing
	# horizontal line (boxdraw)
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | sed 's/\s/─/g'
	# wait for event
	mpc idle player sticker >/dev/null
done

# vi:ft=sh
