#!/bin/sh

# This script is similar to `mpc status` but with more details
# along with the song rating.

# the only option is "-v" for more info
if [ "$1" = '-v' ]; then
	moar_info=1
fi

title='%title%|%name%'
album_date='["%album%" [(%date%)|(%originaldate%)]]|["%album%"]'
artist='%artist%|%albumartist%|%composer%'
formatstr="Title:   [$title]
Album:   [$album_date]
Artist:  [$artist]"
[ -n "$moar_info" ] && formatstr="$formatstr
Genre:   %genre%
Comment: %comment%"
# print the title, album, and artist

get_all_metadata() {
	mpc current -f "$formatstr" 2>/dev/null | grep -v '^[a-zA-Z]*:\s*$'
}

# same as above, but fallback to a file path and include the track rating
print_track_info() {
	# fallback to printing the file path if we find no metadata
	track_metadata="$(get_all_metadata)"
	if [ -z "$track_metadata" ]; then
		mpc current -f '%file%'
	else
		echo "$track_metadata"
	fi
	# also include the song rating
	rating="$(now-playing-rating)"
	if [ "$rating" = 'unrated' ]; then
		echo "Rating:  unrated"
	else
		echo "$rating" | sed -e 's/^rating=/Rating:  /' -e 's|$|/10|'
	fi
}

print_track_info

# vi:ft=sh
