#!/bin/sh

# Uploads a formatted list of my favorite tracks to https://envs.net/~seirdy/music.txt
# by default it only lists tracks I've rated 8 or higher

# shellcheck disable=SC2016
playlist() {
	date -u +"# last updated %Y-%m-%dT%H:%M:%S%:z"
	mpd-playlist-above-rating "$1" \
		| sed -e "s#^#$HOME/Music/#g" \
		| xargs -d '\n' exiftool -q -p '$Artist - $Title' \
		| sort
}
playlist "${1:-8}" | ssh seirdy@envs.sh \
	tee /home/seirdy/public_html/music.txt /home/seirdy/public_gopher/music.txt /home/seirdy/public_gemini/music.txt

# vi:ft=sh
