#!/bin/sh

# Generate a playlist in which tracks rated 6 appear once, tracks rated 7
# appear twice, etc. all the way to tracks rated 10 appearing 4 times.
# The playlist is printed to stdout.

i=6
unsorted_tracks() {
	while [ "$i" -le 10 ]; do
		mpd-playlist-above-rating "$i"
		i=$((i + 1))
	done
}

unsorted_tracks | sort

# vi:ft=sh
