#!/bin/sh
# display current track progrss using MPRIS
# useful for progressbar scripts or xob/wob

# the name of this program
progname="$(basename "${0}")"

help_text="Usage: $progname [OPTION...]

Display current MPRIS track progress as an int from 0-100

Options:
  -h, --help            Print this help and exit
"

usage() {
	printf '%s' "$help_text"
}

# when the user passess bad args, send a msg to stderr and exit
# usage: bad_option <option> <reason>
bad_option() {
	echo "$progname: option $1: $2" >&2
	usage >&2
	exit 1
}

# parse arguments
while [ $# -gt 0 ]; do
	case "$1" in
		-h | --help)
			usage
			exit 0
			;;
		*)
			bad_option "$1" 'invalid option'
			;;
	esac
	shift
done

printf '100*%s\n' "$(mpris-ctl info '%position/%track_length' 2>&1 | sed 's/s//g')" | bc

# vi:ft=sh
